services:
  db:
    image: postgres:17
    container_name: house-service-db
    environment:
      POSTGRES_DB: houses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - houses_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TZ=Europe/Moscow
      - ELASTIC_PASSWORD=your_password
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 10s

  kibana:
    image: kibana:8.11.3
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - TZ=Europe/Moscow
    networks:
      - app-network

volumes:
  houses_data:
  elasticsearch_data:

networks:
  app-network:
