create table if not exists roles(
    id int primary key generated by default as identity,
    name varchar(50) not null
);

create table if not exists users(
    id int primary key generated by default as identity,
    surname varchar(100) not null,
    name varchar(100) not null,
    patronymic varchar(100) not null,
    birth_date date not null,
    document_num varchar(100) not null,
    email varchar(100) unique not null,
    phone varchar(50) unique not null,
    password varchar not null,
    apartment_id int not null,
    role_id int not null references roles(id)
);