create table if not exists users(
      id int primary key generated by default as identity,
      email varchar(100) unique not null,
      password varchar not null,
      name varchar(100) not null,
      surname varchar(100),
      birth_year int,
      role_id int not null references roles(id)
);