create table if not exists applications(
    id int primary key generated by default as identity,
    created_at timestamp without time zone not null,
    author_id int not null,
    topic varchar(200) not null,
    description varchar not null,
    requirement varchar not null,
    status varchar(50) not null
)