services:
  db:
    image: postgres:17
    container_name: auth-service-db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - users_data:/var/lib/postgresql/data

volumes:
  users_data: