create table if not exists streets(
    id int primary key generated by default as identity,
    name varchar(100) unique not null
);

create table if not exists houses(
    id int primary key generated by default as identity,
    street_id int not null references streets(id) on delete cascade,
    number varchar(10) not null
);

create table if not exists apartments(
    id int primary key generated by default as identity,
    house_id int not null references houses(id) on delete cascade,
    entrance_num varchar(10),
    floor_num int,
    apartment_num varchar(10) not null,
    area decimal(5, 1) not null
);