server:
  port: 0

spring:
  application:
    name: house-service
  datasource:
    url: jdbc:postgresql://localhost:5434/houses
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
