server:
  port: 0

spring:
  application:
    name: address-service
  datasource:
    url: jdbc:postgresql://localhost:5434/addresses
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
  elasticsearch:
    uris: http://localhost:9200
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 300000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
